version: '3'
services:
  app:
    build: .
    image: wp1
    container_name: wp_teste
    restart: always
    ports:
      - "8888:80"
    volumes: 
      - ".:/var/www/html/:rw"
    environment: 
      DB_NAME: "wpbeta"
      DB_USER: "root"
      DB_PASSWORD: "@#itsd!2020"
      DB_HOST: "192.168.15.200"
      PORT_WP: "8888"
