version: '3'
services:
  app:
    build: .
    image: wp1
    container_name: wp_teste
    restart: always
    ports:
      - "8888:80"
    volumes: 
      - ".:/var/www/html/:rw"
    environment: 
      APACHE_RUN_USER: "www-data"
      APACHE_RUN_GROUP: "www-data"
